### PR TITLE
[#93688938] Dynamic named AWS environments

### PR DESCRIPTION
**Pull request by mikkoc**
[Create independent environments automatically](https://www.pivotaltracker.com/n/projects/1275640/stories/93688938)

This PR implements the possibility to create isolated and independent AWS environments, based on a parameter passed to Terraform. e.g.:
`terraform apply -var 'env=prod'`

### CODE REVIEW

**Comment by dcarley** [comment]
Thanks for rebasing, much cleaner!

Carrying on the `lifecycle` conversation - I think we should delete it for now. I'm working on a story to remove the ASGs, so we may not need to fix it anyway.

**Comment by mikkoc** [comment]
Rebased and deleted the lifecycle bits. Ready to be merged now.

**Comment by dcarley** [comment]
LGTM.

One late thought: do we need to change hostnames in tsuru-ansible at the same time?

**Comment by mikkoc** [comment]
In tsuru-ansible we need to:
- update the inventory file with new ip addresses and CNAMEs
- update `ssh.config` with the right bastion host CNAME

**Comment by lucorsel** [comment]
In tsuru-ansible we also need to
- update site-aws.yml with the right name of the cluster-specific S3 bucket. Or put that name in the inventory for example.

**Comment by dcarley** [comment]
I guess we can't do that yet, because although we know the new CNAMEs we don't know the IPs.

I had another late thought while riding my bike: are the DNS records going to be difficult to manage when we have many of them? Would it be clearer (albeit longer) to use a sub-domain like `gandalf.prod.tsuru.paas`? Not a blocker to merging this, but worth considering now because it'll be more difficult to change later.

**Comment by jimconner** [comment]
If we're doing subdomains like that is that we'd need a new wildcard cert for each new subdomain. Sadly we can only get certs for `*.domain.com`... not for `*.*.domain.com`

**Comment by mikkoc** [comment]
We'll end up with potentially lots of records, yes, but the filtering of the Route53 will make it very easy to find the records we look for.

**Comment by dcarley** [comment]
Good points, thanks.

I presume that Terraform will destroy the DNS records when we bring down an environment with `terraform destroy`?

**Comment by mikkoc** [comment]
For AWS, yes.
For GCE, we need to wait for version 0.5.0 for that to be possible.

**Comment by dcarley** [comment]
Suffix to be replaced by prefix same as #36

**Comment by dcarley** [comment]
Thanks :+1:

**Pull request merged**
