### PR TITLE
Add basic README

### PR DESCRIPTION
**Pull request by annashipman**

### CODE REVIEW

**Comment by dcarley** [comment]
Should it include an example of how to run it? It is as follows?

```
terraform plan
terraform apply
```

**Comment by annashipman** [comment]
I didn't include that because that seems to me to duplicate the terraform documentation. Does that matter?

**Comment by dcarley** [comment]
Maybe link to an appropriate page in the docs?

**Comment by annashipman** [comment]
I've added a link. Not sure if I'm due a mark on the board though, is "not obvious" acceptable usage?

**Pull request merged**
