### PR TITLE
[#92597874] Added creation of s3 bucket to be used with the registry component

### PR DESCRIPTION
**Pull request by lucorsel**
Simple addition to provision an S3 bucket for use as storage by the registry.

### CODE REVIEW

**Comment by jimconner** [comment]
We should probably be defining the bucket name in our variables.tf and then use that, rather than hard coding the bucket name within the provisioning script.

**Comment by dcarley** [comment]
> We should probably be defining the bucket name in our variables.tf and then use that, rather than hard coding the bucket name within the provisioning script.

:+1:

**Comment by lucorsel** [comment]
Now added variable use from variables.tf

**Comment by jimconner** [comment]
Looks fine to me - Merging.

**Pull request merged**
