### PR TITLE
[#93451408] gce: Replace DNS script with google_dns_record_set

### PR DESCRIPTION
**Pull request by dcarley**
#53 and alphagov/multicloud-deploy#13 must be merged first

---

Terraform 0.5.x now has support for Google Cloud DNS resources. We're going
to upgrade as a result of #53. So we no longer need to use our wrapper
script, meaning that:
- we don't need to configure the `gcloud` utility
- output is cleaner
- records will always be created/updated to reflect the instances or
  forwarding rules that they point to, rather than just when those other
  resources are first created
- old records will be cleaned up by `terraform destroy`

This file has been created by copying `aws/dns-records.tf`, amending the
resource and attribute names to suit GCE, and changing the `rrdatas`
attribute for each to match what `ensure_gce_dns.sh` was doing. I've omitted
the comments because they were no longer correct and it wasn't useful to
maintain the duplicate information.

I have confirmed that the output of `gcloud dns record-sets list` is the
same when creating an environment from the `master` branch and then applying
this branch.

IMPORTANT: Old records from existing environments will need to be deleted
first otherwise you'll get errors like the following:

```
* Error creating DNS RecordSet: googleapi: Error 409: The resource 'entity.change.additions[0]' named 'dcarley-nat.tsuru2.paas.alphagov.co.uk. (A)' already exists, alreadyExists
```

You can use the following script:

```
#!/bin/bash
ZONE_ID=tsuru2
DEPLOY_ENV=dcarley

gcloud dns record-sets transaction start -z ${ZONE_ID}
gcloud dns record-sets list -z ${ZONE_ID} | grep -E "^(\*\.)?${DEPLOY_ENV}-" | while read -a RECORD; do
  gcloud dns record-sets transaction remove -z ${ZONE_ID} \
    --name "${RECORD[0]}" \
    --type "${RECORD[1]}" \
    --ttl "${RECORD[2]}" \
    "${RECORD[3]}"
done
gcloud dns record-sets transaction execute -z ${ZONE_ID}
```

### CODE REVIEW

**Comment by mtekel** [comment]
This won't apply against existing environments (even after repeated apply):

```
google_dns_record_set.router: Creating...
  managed_zone: "" => "tsuru2"
  name:         "" => "michael-hipache.tsuru2.paas.alphagov.co.uk."
  rrdatas.#:    "" => "1"
  rrdatas.0:    "" => "104.155.111.11"
  ttl:          "" => "60"
  type:         "" => "A"
* Error creating DNS RecordSet: googleapi: Error 409: The resource 'entity.change.additions[0]' named 'michael-hipache.tsuru2.paas.alphagov.co.uk. (A)' already exists, alreadyExists
```

This error is actually a good confirmation that the DNS records do match, but terraform simply doesn't remember that the record is there already. Workaround: delete the records manually and let terraform re-create them. Or you can try editing the tfstate file.

This issue doesn't affect new deploys...

**Comment by mtekel** [comment]
This is how it looks inside tfstate:

```
                "google_dns_record_set.api": {
                    "type": "google_dns_record_set",
                    "depends_on": [
                        "google_compute_forwarding_rule.api"
                    ],
                    "primary": {
                        "id": "465",
                        "attributes": {
                            "id": "465",
                            "managed_zone": "tsuru2",
                            "name": "michaeldnstest-api.tsuru2.paas.alphagov.co.uk.",
                            "rrdatas.#": "1",
                            "rrdatas.0": "104.155.104.74",
                            "ttl": "60",
                            "type": "A"
                        }
                    }
                }
```

**Comment by mtekel** [comment]
Workaround with deleting records works. However there's some strange behavior:
- initially terraform only tries to re-create the 6 A records. It doesn't try CNAME record.
- after you delete the A records, it will re-create them, but only then it tries to create that CNAME record - and fails
- if you delete the CNAME record, it will correctly re-create it.

It then went ahead and also re-created all R53 records, destroying old ones first and then creating same ones again. The only change in the tfstate file is that the new records do have `fqdn` property. The record re-creation causes a short outage on the platform. Afterwards all is fine.

**Comment by dcarley** [comment]
Notes:
- I ran the aforementioned script for the CI environment prior to this being merged
- I couldn't reproduce the CNAME problem but I'll keep an eye on CI and we shouldn't see it on new environments in the future anyway
- Per Michal's comments, the last commit does cause DNS records to be recreated in AWS, but besides taking a short time to execute it's fine

**Pull request merged**
