### PR TITLE
[#93548898] aws: Replace ASGs with instances+count

### PR DESCRIPTION
**Pull request by mikkoc**
See https://github.com/alphagov/tsuru-terraform/pull/41

### CODE REVIEW

**Comment by annashipman** [comment]
We need to modify the commit message of the last commit, as @dcarley noted in https://github.com/alphagov/tsuru-terraform/pull/41. We also need to test this against an existing environment.

**Comment by mikkoc** [comment]
Shouldn't we just remove https://github.com/alphagov/tsuru-terraform/commit/76a1d5f32dc30f84c44eb324f746a6512790480a all together?

Changing subnets on an existing environment is really not a daily task: I think it's not fair to expect Terraform (or any other tool for that matter, including Cloudformation!) to handle such a deep core infrastructure change! IMO, new subnets = new environment.

**Comment by mtekel** [comment]
I'd leave the subnets in the 10 range, as this also creates a bit of space in front of them, should we later need to add anything there (e.g. a special hardened/accelerated set of SSL terminating proxies or anything else).

**Comment by annashipman** [comment]
I want to test something here but can't do it now, so I will pick this up on Monday, possibly pairing with @mtekel. Thanks all, and sorry to leave it unfinished on your last day @mikkoc!

**Comment by annashipman** [comment]
I've tested this. Mikko, @mtekel and I have discussed offline and agreed to leave that commit in, so I have rewritten the commit message and rebased.

This probably needs to be reviewed by @jimconner or @actionjack as the rest of us have been involved in it!

**Comment by actionjack** [comment]
LGTM

**Pull request merged**
