### PR TITLE
[#95697144] Firewall: Let nat-ed hosts connect to web

### PR DESCRIPTION
**Pull request by mtekel**
Allow hosts behing NAT, which includes e.g. API server to connect to main web interface of apps deployed on the plaform, which include e.g. postgresapi service broker.

### CODE REVIEW

**Comment by dcarley** [comment]
Bah, forgot to check whether this had a story ID on it. @mtekel could you update Pivotal?

**Comment by mtekel** [comment]
Updated.

**Comment by dcarley** [comment]
I meant could you update Pivotal with a reference to this PR so that the person accepting it knows what has changed. Updating the PR subject won't have any effect now that it's been merged.

**Comment by mtekel** [comment]
I have put a comment in the story: https://www.pivotaltracker.com/n/projects/1275640/stories/95697144 (anna told me to before you asked me to update it)

**Pull request merged**
